apiVersion: v1
kind: Service
metadata:
  name: monitoring-grafana-nodeport
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: monitoring
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30090